# Generated by Django 4.0.5 on 2022-06-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_alter_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
    ]
